# Numpy

- fundamental library for scientific community
- support for array and matrices

In [1]:
import numpy as np

# create array using numpy

# create 1D array

arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
arr2 = np.array([1, 2, 3, 4, 5])
arr2.reshape(1, 5)  # 1 row, 5 cols

array([[1, 2, 3, 4, 5]])

In [4]:
arr3 = np.array([[1, 2, 3, 4, 5]])
arr3.shape

(1, 5)

In [6]:
arr4 = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])
arr4.shape

(2, 5)

In [9]:
np.arange(0, 10, 2).reshape(5, 1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [11]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
# identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Numpy Vectors

In [16]:
v1 = np.array([1, 2, 3, 4, 5])
v2 = np.array([10, 20, 30, 40, 50])

# Elementwise addition
print("addition", v1 + v2)
print("substraction", v1 - v2)
print("multiplication", v1 * v2)

addition [11 22 33 44 55]
substraction [ -9 -18 -27 -36 -45]
multiplication [ 10  40  90 160 250]
